### ISSUE TITLE
Array to string conversion error if a collection is passed as parameter to a context

### ISSUE THREAD

**Issue by mraiffe** [Behat/Symfony2Extension#117]
In symfony 2 parameter.yml
```
parameters:
    mycollection.parameter:
        param: value1
        param2: value2
```
In behat.yml:
```
default:
    suites:
        default:
            contexts:
                - FeatureContext:
                    collection_parameter: "%%mycollection.parameter%%"
    extensions:
        Behat\Symfony2Extension: ~
```
FeatureContext

```
    public function __construct($parameters)
    {
    }
```
The problem probably come from [ServiceArgumentResolver](https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Context/Argument/ServiceArgumentResolver.php#L115) where argument are treated like all arguments are scalar.
