### ISSUE TITLE
Symfony3 param - context class not found and can not be used

### ISSUE THREAD

**Issue by FabianPiconeDev** [Behat/Symfony2Extension#127]
behat/behat v3.3.1 
behat/symfony2-extension 2.1.1 
symfony/symfony v3.3.9

```
default:
  extensions:
    Behat\Symfony2Extension: ~
  suites:
      foo-suite:
        - Foo\Bar\Baz\ApiContext
                fooArg: 1
```
I receive
```
  [Behat\Behat\Context\Exception\ContextNotFoundException]                      
  `Foo\Bar\Baz\ApiContext fooArg: 1` context class not found and can not be used.
```

Like it does not recognize that `fooArg` should be a param of `ApiContext`.

When i remove `fooArg: 1` the class `ApiContext` is found and the test starts.
