### ISSUE TITLE
Enable Symfony DI autowiring

### ISSUE THREAD

**Issue by vincentchalamon** [Behat/Symfony2Extension#128]
As a bridge with Symfony2, it should be interesting to autowire contexts arguments using Symfony DI autowiring, if they're detected as Symfony services. For instance:
```yaml
# behat.yml
default:
    suites:
        default:
            contexts:
                - FeatureContext: ~
    extensions:
        Behat\Symfony2Extension:
            kernel:
                bootstrap: 'vendor/autoload.php'
                path: 'src/Kernel.php'
                class: 'App\Kernel'
```
```php
class FeatureContext implements Context
{
    private $clientManager;
    private $tokenManager;

    public function __construct(ClientManagerInterface $clientManager, TokenManagerInterface $tokenManager)
    {
        $this->clientManager = $clientManager;
        $this->tokenManager = $tokenManager;
    }

    // ...
}
```
