### ISSUE TITLE
default to first class detected between App\Kernel and AppKernel

### ISSUE THREAD

**Issue by greg0ire** [Behat/Symfony2Extension#140]
I had to configure the extension like this:

```yaml
        Behat\Symfony2Extension:
            kernel:
                path: src/Kernel
                class: App\Kernel
```

I don't want to have to do this, so I'll contribute a fix later.
