### ISSUE TITLE
Support .env.test

### ISSUE THREAD

**Issue by XavierVallot** [Behat/Symfony2Extension#146]
Hi, 
regarding the recent Symfony evolutions (https://symfony.com/doc/current/configuration/dot-env-changes.html#updating-my-application), do you plan to add support for `.env.test` file ? 
Thank you !

**Comment by claudusd** [comment]
Hi, 

I think, this is already implemented. You should set the the bootstrap file path in your configuration. 
By default the bootstrap's path is ``app/autoload.php``. Now the bootstrap's path is ``config/bootstrap.php``

``` yaml
default:
  extensions:
    Behat\Symfony2Extension:
      kernel:
        bootstrap: config/bootstrap.php
```

The support of ``.env.*`` is provided by the new [config.php](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/bootstrap.php).

**Comment by kevin-lot** [comment]
What about this file : https://github.com/symfony/recipes/blob/master/behat/symfony2-extension/2.1/features/bootstrap/bootstrap.php ?

```
bootstrap.php set 'APP_ENV='.$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = 'test'
```

```
default:
    extensions:
        Behat\Symfony2Extension:
            kernel:
                bootstrap: 'features/bootstrap/bootstrap.php'
                class: 'App\Kernel'
```
