### ISSUE TITLE
Difference between parameter injection and access to `getContainer`

### ISSUE THREAD

**Issue by jdeniau** [Behat/Symfony2Extension#148]
Hi,

I just discover a small difference between access `getContainer` from the `KernelDictionary::getContainer()`. 

If I understand correctly, the kernel is rebooted [after each scenario](https://github.com/Behat/Symfony2Extension/blob/31258ea704144c2cd55db1ce58de000c5d59a77b/src/Behat/Symfony2Extension/Context/Initializer/KernelAwareInitializer.php#L68-L72)  or [if we call an http request from symfony framework client](https://github.com/symfony/symfony/blob/adb137d5c1f5c2b0831b5135c0e171b46bac81ca/src/Symfony/Bundle/FrameworkBundle/Client.php#L119).

This mean that all services are reinitialized, and particularly doctrine entity managers.

But's that is not really the recommended way of doing this in Symfony 3+ (private services, autowiring, etc.).

On the other hand, if we do inject doctrine as a parameter in `behat.yml` like this :
```yaml
default:
  suites:
    default:
      contexts:
        - Mapado\TicketingBundle\Tests\Context\TransactionContext:             
          - '@doctrine.orm.default_entity_manager'
```
Then the instance of entity manager is not reinitialized when the kernel is rebooted (and thus the unit of work is not "cleared").

I made a "patch" with a context that clear every unit of work after each step, but it's a bit weird, and other users may have similar bugs.

1. What is the way you recommend about that ? 
2. Is there something we can do in this bundle to prevent that kind of bug ? (maybe re-initialize every contexts after each scenario / steps ?)
3. May I help with an implementation or does it have to wait after #128 is resolved ?

Thanks
