### ISSUE TITLE
@BundleName does not work with Symfony 2.1.1

### ISSUE THREAD

**Issue by Markkaz** [Behat/Symfony2Extension#15]
I installed a clean installation of Symfony 2.1.1 via composer:

```
php composer.phar create-project symfony-framework-standard-edition Symfony-2.1 2.1.1
```

After that I added Behat and the Symfony2-extension of Behat to the project:

``` json
"require": {
        "behat/behat": "2.4.*@stable",
        "behat/mink-extension": "*",
        "behat/mink-browserkit-driver": "*",
        "behat/symfony2-extension": "*"
}
```

After running composer update, you can run behat via bin/behat, but it does not work correctly.
The default Symfony 2 installation contains the AcmeDemoBundle, so I tried to initialize behat for the AcmeDemoBundle using the following command:

```
bin/behat --init @AcmeDemoBundle
```

But when running this command I get the following error from Behat:

```
[InvalidArgumentException]
Provide features argument in order to init suite.
```

And when I add the features argument I get the following error:

```
[InvalidArgumentException]
Can not find bundle to initialize suite.
```

I put the following behat.yml in the root directory of the Symfony installation:

``` yml
default:
    extensions:
        Behat\MinkExtension\Extension:
            base_url: http://localhost/app_dev.php/Symfony-2.1/web/app_dev.php
            default_session: 'symfony2'
        Behat\Symfony2Extension\Extension:
            mink_driver: true
```
