### ISSUE TITLE
Environment variable not found: "DATABASE_URL".

### ISSUE THREAD

**Issue by ahmedtoolapp** [Behat/Symfony2Extension#159]
I am using Symfony2Extension with a new installation of Symfony 5.1 with PHP 7.3
I tried to launch vendor/bin/behat

I have my feature displayed but with an error
```
In EnvVarProcessor.php line 171:
Environment variable not found: "DATABASE_URL".
```

**Comment by kadzany** [comment]
Have you solved this issue @ahmedtoolapp ?

**Comment by mtarld** [comment]
This error means that the bootstrap file isn't loaded. Indeed, the `boostrap.php` is responsible to load the Symfony's DotEnv component.

Therefore, have a look at your `behat.yml` file and make sure that the bootstrap file path is correctly configured. 

Eg:
```yaml
extensions:
    Behat\Symfony2Extension:
        kernel:
            bootstrap: features/bootstrap/bootstrap.php
            class: App\Kernel
```
