### ISSUE TITLE
Cannot switch kernel's environment 

### ISSUE THREAD

**Issue by Taluu** [Behat/Symfony2Extension#28]
Hi,
I have the following config in my behat.yml :

``` yml
default:
  context:
    class : 'features\bootstrap\Context\FeatureContext'
    parameters:
      reset_database  : false
      environment      : prod
      debug               : false
  formatter:
    name: progress
  extensions:
    Behat\Symfony2Extension\Extension:
      mink_driver: true

      kernel:
        env: prod

    Behat\Symfony2Extension\Extension:
      mink_driver: true
    Behat\MinkExtension\Extension:
      base_url : 'http://localhost/'
      goutte   :
        guzzle_parameters :
          curl.options     :
            CURLOPT_CONNECTTIMEOUT : 0
            CURLOPT_TIMEOUT        : 900

      default_session: goutte
```

And, in my context, using the Symfony2Extension, I have the following :

``` php
<?php
// with proper uses...

class ConsoleContext extends BehatContext
{
    use KernelDictionary;

    /** @var Application */
    private $application = null;

    /** CommandTester */
    private $tester = null;

    /** @When /^(?:I )?run the command "(?P<name>(?:[^"]|\\")+)"$/ */
    public function iRunCommand($name)
    {
        if (null === $this->application) {
            $this->application = new Application($this->getKernel());

            // register bundles commands... I guess.
            foreach ($this->getKernel()->getBundles() as $bundle) {
                if ($bundle instanceof Bundle) {
                    $bundle->registerCommands($this->application);
                }
            }
        }

        var_dump($this->getKernel()->getEnvironment());

        $command = $this->application->find($name);

        $this->tester = new CommandTester($command);
        $this->tester->execute(['command' => $command->getName()]);
    }

    /** @Then /^the console should have displayed "(?P<output>(?:[^"]|\\")+)"$/ */
    public function consoleShouldHaveDisplayed($output)
    {
        if (null === $this->tester) {
            throw new Exception('No command were run');
        }

        echo $this->tester->getDisplay();
    }
}
```

With the `var_dump`, I always have the result `string(4) "test"`. So I don't know if I'm doing something wrong, but it seems I can't change the kernel environment from my config file... ?

By the way, would there be a cleaner way to initialize the console, as I need to run some behaviour tests on it ?

Thanks !
