### ISSUE TITLE
Testing Pages requiring Authentication.

### ISSUE THREAD

**Issue by reecefowell** [Behat/Symfony2Extension#34]
I have looked around, and i have not been able to find a way to do this.

Is there a method in Symfony2Extension to test authenticated pages with the test database?

i.e;

``` YAML
# app/config/config_test.yml
doctrine:
    dbal:
        dbname:   %database_name%_test
```

and do something like what is shown [here](http://stackoverflow.com/questions/11261647/authentication-with-behat-and-symfony2)? Of course this does not work, but how else can we test authenticated pages without traversing to the login page, logging in for every test case scenario? Is it possible and how?

Thanks in advance.
