### ISSUE TITLE
Load multiple .feature files Edit

### ISSUE THREAD

**Issue by pedroresende** [Behat/Symfony2Extension#42]
It would be nice to allow to import multiple .feature files, for instance

``` yml
default:
  paths:
    features:
      - '@testbundle/Features/'
      - '@testbundle2/Features/'
```

allowing to run all the scenarios described on those files.
