### ISSUE TITLE
Cannot run features in another directory

### ISSUE THREAD

**Issue by aequasi** [Behat/Symfony2Extension#53]
I'm probably doing something wrong, but i cant seem to get behat to find and run my features when they arent in the bundle.

my dir structure:

```
app
src
    AcmeBundle
tests
    AcmeBundle
        Features
           Context
               FeatureContext.php
           demo.feature
behat.yml
```

***behat.yml***
```yml
default:
    suites:
        analytics:
            type: symfony_bundle
            bundle: AcmeDemoBundle
            paths: [ %paths.base%/./tests/DemoBundle/Features ]
            contexts: [ Acme\DemoBundle\Features\Context\FeatureContext ]
    formatters:
        pretty: true
    extensions:
        Behat\Symfony2Extension\Extension: ~
```

When i move them into the bundle, without paths, they work
