### ISSUE TITLE
behat --init fails if application level feature suite is used

### ISSUE THREAD

**Issue by kimu** [Behat/Symfony2Extension#61]
If application level feature suite is used `behat --init` fails returning the following error

```
[InvalidArgumentException]
  Provide features argument in order to init suite.
```

The configuration in behat.yml is the following

```
default:
    paths:
        features: features
        bootstrap: %behat.paths.features%/bootstrap
    context:
        class: Infinity\Bundle\TestBundle\Test\Context\FeatureContext
    formatter:
        name: pretty
    extensions:
        Behat\MinkExtension\Extension:
            base_url: 'http://localhost'
            goutte:    ~
            selenium2: ~
            default_session: goutte
            javascript_session: selenium2
            browser_name: firefox
        Behat\Symfony2Extension\Extension: ~
```

The error suggests that `behat --init` expect a bundle or suite name as argument to be initialised even if such feature is not used. 

The only way to run `behat --init` correctly is to comment out `Behat\Symfony2Extension\Extension: ~` temporarily.

Symfony2Extension should be able to understand how is used based on the configuration and do not intercede with `behat --init` in case application level feature suite is used.
