### ISSUE TITLE
It is apparently impossible to use multiple contexts in a suite if using Symfony2Extension

### ISSUE THREAD

**Issue by Tocacar** [Behat/Symfony2Extension#86]
@everzet  Sorry for opening this originally in the Behat respository.  

I have tried every config combination humanly possible, but cannot get two contexts to run. As soon as I add a 'contexts:' key to my config, even the FeatureContext class is no longer recognised.

This is my behat.yml file:

```
default:
    suites:
      my_suite:
        type: symfony_bundle
        bundle: MyCoolBundle
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            base_url: http://ams.ldev
            selenium2: ~
            symfony2: ~
            sessions:
                default:
                    symfony2: ~
```

And I have the default directory structure created by the behat init command. How can I change the above config to allow me to have two context classes for the suite?

Ideally I'd like to define a 'global' context class that contains database-related code that should run on each execution of my tests. But if I can even just get this working inside one suite that'd do me for now.

Thanks for any help.

**Comment by stof** [comment]
Well, if you define the ``contexts`` key, the extension will not register the ``MyCoolBundle\Features\Context\FeatureContext`` automatically anymore. This is expected to be consistent with the way Behat itself registers the ``FeatureContext`` class only when the context is not configured explicitly.

So if you use multiple contexts, you need to register the ``MyCoolBundle\Features\Context\FeatureContext`` explicitly too

**Comment by Tocacar** [comment]
Hi @stof thanks for your reply.  

I know you have to do that too.  And I've even tried defining paths and putting one of the context classes in /features/bootstrap instead of alongside the FeaturesContext class in the mimicked bundle path.  Nothing seems to work though.

If you have a working configuration example, perhaps you could share it.  The examples in the docs I have tried several times, to no avail.

**Comment by stof** [comment]
@Tocacar please paste your config with the contexts in it.

**Comment by Tocacar** [comment]
@stof Sorry for the delay in responding - I had to wait until my lunchbreak.  

I set this up again and gave it a quick run through to make sure I wasn't being stupid and....guess what.  I am.  The motto of this story is don't drink wine and write tests.  Thank you for attempting to help me anyway. 

In case this helps any other poor fool out there, here is my config which, it turns out, does actually work:

```
default:
  extensions:
    Behat\Symfony2Extension: ~
    Behat\MinkExtension:
      base_url: http://my-production-url.lprod
      selenium2: ~
      symfony2: ~
      sessions:
        default:
          symfony2: ~
  suites:
    colony_suite:
      type: symfony_bundle
      bundle: MyAppMyBundle
      contexts:
        - MyApp\MyBundle\Features\Context\FeatureContext
        - MyApp\MyBundle\Features\Context\DatabaseContext

chrome:
  extensions:
    Behat\MinkExtension:
      browser_name: chrome

firefox:
  extensions:
    Behat\MinkExtension:
      browser_name: firefox
```

Both DatabaseContext and FeatureContext classes are in the default directory structure created by Behat for a Symfony bundle and have namespaces (hence the longer config path to each above).
