### ISSUE TITLE
Referencing container parameters in behat.yml

### ISSUE THREAD

**Issue by aleixverges** [Behat/Symfony2Extension#91]
Hi,
     Since the last release, it seems that container parameters con be referenced in behat.yml file. Could you explain how that should be done? I tried to do it with no success.

Thanks

**Comment by stof** [comment]
They can be used only for the arguments of contexts when initializing, not in the whole parameters.yml

The syntax is the same than in Symfony: ``%my_param%``

**Comment by aleixverges** [comment]
Can you please paste a short example? I think that's the way I'm doing it, but even with that there's something I'm doing wrong

Thanks

**Comment by aleixverges** [comment]
Just to give you a short example. This is what I'm doing:
- In my parameteres.yml file:
     parameters:
          my_param: some_value

- In my behat.yml file:
default:
  suites:
    suite1:
      paths:
        - %paths.base%/src/Tests/Functional/features/xxxxxxxx
      contexts:
        - SomeContext:
            theParameter: %my_param%

**Comment by stof** [comment]
@ciaranmcnulty as you worked on the feature, can you have a look at this ?

**Comment by ciaranmcnulty** [comment]
I can't check right now but that looks correct IIRC. Will try and reproduce

**Comment by stof** [comment]
@ciaranmcnulty please add a Behat scenario covering the feature when reproducing it.

**Comment by aleixverges** [comment]
@stof @ciaranmcnulty Hi, any updates on this issue?

Thanks

**Comment by sroze** [comment]
The parameters needs to be escaped. Your `behat.yml` file becomes:
```yml
default:
  suites:
    suite1:
      paths:
        - %paths.base%/src/Tests/Functional/features/xxxxxxxx
      contexts:
        - SomeContext:
            theParameter: %%my_param%%
```

I've created #102 to add the example in the tests.
